"""Add advanced features

Revision ID: 0886646b5041
Revises: d4dea75d2bda
Create Date: 2026-07-06 23:58:10.462016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0886646b5041'
down_revision: Union[str, Sequence[str], None] = 'd4dea75d2bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('pcr_ratio', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('sentiment_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'sentiment_score')
    op.drop_column('market_data', 'pcr_ratio')
    # ### end Alembic commands ###
