"""Add status and risk_reward_ratio

Revision ID: 5c2f2b7c68a3
Revises: 0886646b5041
Create Date: 2026-07-09 12:11:44.310139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2f2b7c68a3'
down_revision: Union[str, Sequence[str], None] = '0886646b5041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('predictions', sa.Column('risk_reward_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'risk_reward_ratio')
    op.drop_column('predictions', 'status')
    # ### end Alembic commands ###
